In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('vehicles.csv')

In [3]:
df.head()

,id,url,region,region_url,price,year,manufacturer,model,condition,cylinders,...,size,type,paint_color,image_url,description,county,state,lat,long,posting_date
0,7222695916,https://prescott.craigslist.org/cto/d/prescott...,prescott,https://prescott.craigslist.org,6000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,az,NaN,NaN,NaN
1,7218891961,https://fayar.craigslist.org/ctd/d/bentonville...,fayetteville,https://fayar.craigslist.org,11900,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ar,NaN,NaN,NaN
2,7221797935,https://keys.craigslist.org/cto/d/summerland-k...,florida keys,https://keys.craigslist.org,21000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,fl,NaN,NaN,NaN
3,7222270760,https://worcester.craigslist.org/cto/d/west-br...,worcester / central MA,https://worcester.craigslist.org,1500,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ma,NaN,NaN,NaN
4,7210384030,https://greensboro.craigslist.org/cto/d/trinit...,greensboro,https://greensboro.craigslist.org,4900,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,nc,NaN,NaN,NaN

In [4]:
print('Dataset Info:')
df.info()

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 426880 entries, 0 to 426879
Data columns (total 26 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            426880 non-null  int64
 1   url           426880 non-null  object
 2   region        426880 non-null  object
 3   region_url    426880 non-null  object
 4   price         426880 non-null  int64
 5   year          425675 non-null  float64
 6   manufacturer  409234 non-null  object
 7   model         421603 non-null  object
 8   condition     252776 non-null  object
 9   cylinders     249202 non-null  object
 10  fuel          423867 non-null  object
 11  odometer      422480 non-null  float64
 12  title_status  418638 non-null  object
 13  transmission  424324 non-null  object
 14  VIN           265838 non-null  object
 15  drive         296313 non-null  object
 16  size          120519 non-null  object
 17  type          334022 non-null  object
 18  paint_color   296677 non-null  object
 19  image_url     426812 non-null  object
 20  description   426810 non-null  object
 21  county        0 non-null       float64
 22  state         426880 non-null  object
 23  lat           420331 non-null  float64
 24  long          420331 non-null  float64
 25  posting_date  426812 non-null  object
dtypes: float64(5), int64(2), object(19)
memory usage: 84.7+ MB

In [5]:
print('\nMissing Values:')
print(df.isnull().sum())

Missing Values:
id                   0
url                  0
region               0
region_url           0
price                0
year              1205
manufacturer     17646
model             5277
condition       174104
cylinders       177678
fuel              3013
odometer          4400
title_status      8242
transmission      2556
VIN             161042
drive           130567
size            306361
type             92858
paint_color     130203
image_url           68
description         70
county          426880
state                0
lat               6549
long              6549
posting_date        68
dtype: int64

In [6]:
# Calculate and display percentage of missing values for all columns
missing_percentages = (df.isnull().sum()/len(df)*100)  # Calculate percentage of missing values
missing_df = missing_percentages.to_frame(name='Missing Values')  # Convert to dataframe
missing_sorted = missing_df.sort_values('Missing Values', ascending=False)  # Sort by missing values percentage
print(missing_sorted)

              Missing Values
county            100.000000
size               71.767476
cylinders          41.622470
condition          40.785232
VIN                37.725356
drive              30.586347
paint_color        30.501078
type               21.752717
manufacturer        4.133714
title_status        1.930753
lat                 1.534155
long                1.534155
model               1.236179
odometer            1.030735
fuel                0.705819
transmission        0.598763
year                0.282281
description         0.016398
posting_date        0.015930
image_url           0.015930
region_url          0.000000
url                 0.000000
id                  0.000000
region              0.000000
price               0.000000
state               0.000000

In [7]:
df.shape

(426880, 26)

In [8]:
def show_detailed_categories(df, top_n=10):
    categorical_columns = df.select_dtypes(include=['object', 'category']).columns
    
    for col in categorical_columns:
        print(f"\nAnalysis for: {col}")
        print("-" * 50)
        
        # Get value counts and percentages
        counts = df[col].value_counts()
        percentages = df[col].value_counts(normalize=True) * 100
        
        # Create summary DataFrame
        summary = pd.DataFrame({
            'Count': counts,
            'Percentage': percentages.round(2),
            'Cumulative_Percentage': percentages.cumsum().round(2)
        })
        
        # Show top N categories
        print(f"Top {top_n} categories:")
        print(summary.head(top_n))
        
        # Show basic statistics
        print(f"\nTotal categories: {len(counts)}")
        print(f"Missing values: {df[col].isnull().sum()} ({(df[col].isnull().sum()/len(df)*100):.2f}%)")

# Use the function
show_detailed_categories(df, top_n=5)

Analysis for: url
--------------------------------------------------
Top 5 categories:
                                                    Count  Percentage  \
url
https://wyoming.craigslist.org/ctd/d/conrad-201...      1         0.0
https://wyoming.craigslist.org/ctd/d/conrad-201...      1         0.0
https://wyoming.craigslist.org/ctd/d/conrad-201...      1         0.0
https://wyoming.craigslist.org/ctd/d/conrad-201...      1         0.0
https://wyoming.craigslist.org/ctd/d/billings-2...      1         0.0

                                                    Cumulative_Percentage
url
https://wyoming.craigslist.org/ctd/d/conrad-201...                    0.0
https://wyoming.craigslist.org/ctd/d/conrad-201...                    0.0
https://wyoming.craigslist.org/ctd/d/conrad-201...                    0.0
https://wyoming.craigslist.org/ctd/d/conrad-201...                    0.0
https://wyoming.craigslist.org/ctd/d/billings-2...                    0.0

Total categories: 426880
Missing values: 0 (0.00%)

Analysis for: region
--------------------------------------------------
Top 5 categories:
                         Count  Percentage  Cumulative_Percentage
region
columbus                  3608        0.85                   0.85
jacksonville              3562        0.83                   1.68
spokane / coeur d'alene   2988        0.70                   2.38
eugene                    2985        0.70                   3.08
fresno / madera           2983        0.70                   3.78

Total categories: 404
Missing values: 0 (0.00%)

Analysis for: region_url
--------------------------------------------------
Top 5 categories:
                                Count  Percentage  Cumulative_Percentage
region_url
https://spokane.craigslist.org   2988         0.7                    0.7
https://eugene.craigslist.org    2985         0.7                    1.4
https://orlando.craigslist.org   2983         0.7                    2.1
https://fresno.craigslist.org    2983         0.7                    2.8
https://bend.craigslist.org      2982         0.7                    3.5

Total categories: 413
Missing values: 0 (0.00%)

Analysis for: manufacturer
--------------------------------------------------
Top 5 categories:
              Count  Percentage  Cumulative_Percentage
manufacturer
ford          70985       17.35                  17.35
chevrolet     55064       13.46                  30.80
toyota        34202        8.36                  39.16
honda         21269        5.20                  44.36
nissan        19067        4.66                  49.02

Total categories: 42
Missing values: 17646 (4.13%)

Analysis for: model
--------------------------------------------------
Top 5 categories:
                Count  Percentage  Cumulative_Percentage
model
f-150            8009        1.90                   1.90
silverado 1500   5140        1.22                   3.12
1500             4211        1.00                   4.12
camry            3135        0.74                   4.86
silverado        3023        0.72                   5.58

Total categories: 29667
Missing values: 5277 (1.24%)

Analysis for: condition
--------------------------------------------------
Top 5 categories:
            Count  Percentage  Cumulative_Percentage
condition
good       121456       48.05                  48.05
excellent  101467       40.14                  88.19
like new    21178        8.38                  96.57
fair         6769        2.68                  99.25
new          1305        0.52                  99.76

Total categories: 6
Missing values: 174104 (40.79%)

Analysis for: cylinders
--------------------------------------------------
Top 5 categories:
              Count  Percentage  Cumulative_Percentage
cylinders
6 cylinders   94169       37.79                  37.79
4 cylinders   77642       31.16                  68.94
8 cylinders   72062       28.92                  97.86
5 cylinders    1712        0.69                  98.55
10 cylinders   1455        0.58                  99.13

Total categories: 8
Missing values: 177678 (41.62%)

Analysis for: fuel
--------------------------------------------------
Top 5 categories:
           Count  Percentage  Cumulative_Percentage
fuel
gas       356209       84.04                  84.04
other      30728        7.25                  91.29
diesel     30062        7.09                  98.38
hybrid      5170        1.22                  99.60
electric    1698        0.40                 100.00

Total categories: 5
Missing values: 3013 (0.71%)

Analysis for: title_status
--------------------------------------------------
Top 5 categories:
               Count  Percentage  Cumulative_Percentage
title_status
clean         405117       96.77                  96.77
rebuilt         7219        1.72                  98.49
salvage         3868        0.92                  99.42
lien            1422        0.34                  99.76
missing          814        0.19                  99.95

Total categories: 6
Missing values: 8242 (1.93%)

Analysis for: transmission
--------------------------------------------------
Top 5 categories:
               Count  Percentage  Cumulative_Percentage
transmission
automatic     336524       79.31                  79.31
other          62682       14.77                  94.08
manual         25118        5.92                 100.00

Total categories: 3
Missing values: 2556 (0.60%)

Analysis for: VIN
--------------------------------------------------
Top 5 categories:
                   Count  Percentage  Cumulative_Percentage
VIN
1FMJU1JT1HEA52352    261        0.10                   0.10
3C6JR6DT3KG560649    235        0.09                   0.19
1FTER1EH1LLA36301    231        0.09                   0.27
5TFTX4CN3EX042751    227        0.09                   0.36
1GCHTCE37G1186784    214        0.08                   0.44

Total categories: 118264
Missing values: 161042 (37.73%)

Analysis for: drive
--------------------------------------------------
Top 5 categories:
        Count  Percentage  Cumulative_Percentage
drive
4wd    131904       44.52                  44.52
fwd    105517       35.61                  80.13
rwd     58892       19.87                 100.00

Total categories: 3
Missing values: 130567 (30.59%)

Analysis for: size
--------------------------------------------------
Top 5 categories:
             Count  Percentage  Cumulative_Percentage
size
full-size    63465       52.66                  52.66
mid-size     34476       28.61                  81.27
compact      19384       16.08                  97.35
sub-compact   3194        2.65                 100.00

Total categories: 4
Missing values: 306361 (71.77%)

Analysis for: type
--------------------------------------------------
Top 5 categories:
        Count  Percentage  Cumulative_Percentage
type
sedan   87056       26.06                  26.06
SUV     77284       23.14                  49.20
pickup  43510       13.03                  62.23
truck   35279       10.56                  72.79
other   22110        6.62                  79.41

Total categories: 13
Missing values: 92858 (21.75%)

Analysis for: paint_color
--------------------------------------------------
Top 5 categories:
             Count  Percentage  Cumulative_Percentage
paint_color
white        79285       26.72                  26.72
black        62861       21.19                  47.91
silver       42970       14.48                  62.40
blue         31223       10.52                  72.92
red          30473       10.27                  83.19

Total categories: 12
Missing values: 130203 (30.50%)

Analysis for: image_url
--------------------------------------------------
Top 5 categories:
                                                    Count  Percentage  \
image_url
https://images.craigslist.org/00N0N_1xMPvfxRAId...   7357        1.72
https://images.craigslist.org/00R0R_lwWjXSEWNa7...   2192        0.51
https://images.craigslist.org/01111_l590CdXzJSo...    276        0.06
https://images.craigslist.org/01313_9Zne268YnWZ...    231        0.05
https://images.craigslist.org/00X0X_1cMDo5xqSuA...    227        0.05

                                                    Cumulative_Percentage
image_url
https://images.craigslist.org/00N0N_1xMPvfxRAId...                   1.72
https://images.craigslist.org/00R0R_lwWjXSEWNa7...                   2.24
https://images.craigslist.org/01111_l590CdXzJSo...                   2.30
https://images.craigslist.org/01313_9Zne268YnWZ...                   2.36
https://images.craigslist.org/00X0X_1cMDo5xqSuA...                   2.41

Total categories: 241899
Missing values: 68 (0.02%)

Analysis for: description
--------------------------------------------------
Top 5 categories:
                                                    Count  Percentage  \
description
35 VEHICLES PRICED UNDER $3000!!!  BIG TIME! TA...    231        0.05
Call or text today to find out more. (602) 620-...    197        0.05
This truck has sold, but we buy trucks like thi...    154        0.04
CREDIT CARS- $700.00 DOWN- RIGHT ON THE CORNER,...    148        0.03
HEC LEASING, LLC Call Gary, Russ or Clay at 888...    133        0.03

                                                    Cumulative_Percentage
description
35 VEHICLES PRICED UNDER $3000!!!  BIG TIME! TA...                   0.05
Call or text today to find out more. (602) 620-...                   0.10
This truck has sold, but we buy trucks like thi...                   0.14
CREDIT CARS- $700.00 DOWN- RIGHT ON THE CORNER,...                   0.17
HEC LEASING, LLC Call Gary, Russ or Clay at 888...                   0.20

Total categories: 360911
Missing values: 70 (0.02%)

Analysis for: state
--------------------------------------------------
Top 5 categories:
       Count  Percentage  Cumulative_Percentage
state
ca     50614       11.86                  11.86
fl     28511        6.68                  18.54
tx     22945        5.38                  23.91
ny     19386        4.54                  28.45
oh     17696        4.15                  32.60

Total categories: 51
Missing values: 0 (0.00%)

Analysis for: posting_date
--------------------------------------------------
Top 5 categories:
                          Count  Percentage  Cumulative_Percentage
posting_date
2021-04-23T22:13:05-0400     12         0.0                   0.00
2021-04-13T13:19:15-0500     11         0.0                   0.01
2021-04-22T20:32:05-0400     11         0.0                   0.01
2021-04-16T12:07:56-0500     10         0.0                   0.01
2021-04-30T10:01:13-0400      9         0.0                   0.01

Total categories: 381536
Missing values: 68 (0.02%)